name: Terraria Server

on:
  workflow_dispatch:

jobs:
  start-terraria:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y unzip

    - name: Download Terraria Server
      run: |
        mkdir -p terraria-server
        cd terraria-server
        wget https://terraria.org/api/download/pc-dedicated-server/terraria-server-1436.zip -O terraria-server.zip
        unzip terraria-server.zip
        chmod +x ./Linux/TerrariaServer.bin.x86_64

    - name: Start Terraria Server
      run: |
        cd terraria-server/Linux
        ./TerrariaServer.bin.x86_64 -config ../../serverconfig.txt
