name: Terraria Server

on:
  workflow_dispatch:

jobs:
  start-terraria:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Update and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget

    - name: Download Terraria Server
      run: |
        mkdir -p terraria-server
        cd terraria-server
        wget https://terraria.org/api/download/pc-dedicated-server/terraria-server-1436.zip -O terraria-server.zip
        ls -lh terraria-server.zip

    - name: Unzip Terraria Server
      run: |
        cd terraria-server
        unzip terraria-server.zip
        ls -R  # Kiểm tra cấu trúc file và thư mục sau khi giải nén

    - name: Set executable permissions with sudo
      run: sudo chmod +x terraria-server/Linux/TerrariaServer.bin.x86_64

    - name: Start Terraria Server
      run: |
        cd terraria-server/Linux
        ./TerrariaServer.bin.x86_64 -config ../../serverconfig.txt
