name: Terraria Server

on:
  workflow_dispatch:

jobs:
  start-terraria:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Update and install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget

    - name: Download Terraria Server
      run: |
        mkdir -p terraria-server
        cd terraria-server
        wget https://terraria.org/api/download/pc-dedicated-server/terraria-server-1436.zip -O terraria-server.zip
        ls -lh terraria-server.zip  # Kiểm tra file zip đã tải về

    - name: Unzip Terraria Server
      run: |
        cd terraria-server
        unzip terraria-server.zip
        ls -R  # Liệt kê tất cả thư mục và file sau khi giải nén để kiểm tra vị trí file thực thi

    - name: Check directory structure after unzip
      run: |
        cd terraria-server
        ls -R  # Kiểm tra cấu trúc thư mục của Terraria server sau khi giải nén

    - name: Find the TerrariaServer file
      run: |
        find terraria-server -name "TerrariaServer.bin.x86_64"  # Tìm vị trí chính xác của file thực thi

    - name: Set executable permissions
      run: |
        sudo chmod +x $(find terraria-server -name "TerrariaServer.bin.x86_64")  # Cấp quyền thực thi cho file tìm được

    - name: Start Terraria Server
      run: |
        cd $(dirname $(find terraria-server -name "TerrariaServer.bin.x86_64"))  # Di chuyển vào thư mục chứa file thực thi
        ./TerrariaServer.bin.x86_64 -config ../../serverconfig.txt
